"""create_video_job_and_detection_tables

Revision ID: 68baaf9b657b
Revises: 981268d84e14
Create Date: 2026-07-16 15:34:15.961559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68baaf9b657b'
down_revision: Union[str, Sequence[str], None] = '981268d84e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_status'), 'video_jobs', ['status'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_job_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('crop_path', sa.String(length=512), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_job_id'], ['video_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_track_id'), 'detections', ['track_id'], unique=False)
    op.create_index(op.f('ix_detections_video_job_id'), 'detections', ['video_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_video_job_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_track_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_video_jobs_status'), table_name='video_jobs')
    op.drop_table('video_jobs')
    # ### end Alembic commands ###
